name: Dismiss PR Approval

on:
  pull_request_review:
    types: [submitted]  # Trigger when a review is submitted (approved, changes requested, etc.)

jobs:
  dismiss-approval:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}        

      - name: Get Authors of Commits in the PR
        id: commits
        run: |
          # Fetch the commits
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          PR_COMMITS=$(curl -L -k \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-Github-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/commits")
          echo "$PR_COMMITS"
          # Extract commit authors
          COMMITS_AUTHORS=$(echo "$PR_COMMITS" | jq -r '.[].author.login' | sort | uniq | paste -sd, -)
          
          # Set the authors as an environment variable
          echo "commits_authors=$COMMITS_AUTHORS" >> $GITHUB_ENV
          echo "$COMMITS_AUTHORS"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate API calls
          
      - name: Get the reviewer and committer details
        id: review
        run: |
          # Extract the reviewer who submitted the review
          REVIEWER=$(jq --raw-output '.review.user.login' < $GITHUB_EVENT_PATH)
          
          # Access the list of commit authors from the previous step
          COMMITS_AUTHORS=${{ env.commits_authors }}

          # Convert the comma-separated authors into an array
          IFS=',' read -r -a authors_array <<< "$COMMITS_AUTHORS"
          
          # Loop through each author to check if the reviewer is one of them
          for author in "${authors_array[@]}"; do
            if [ "$author" == "$REVIEWER" ]; then
              # Dismiss the review if the reviewer is also a commit author
              echo "Review submitted by $REVIEWER is from a committer. Dismissing review..."
              curl -L -k \
                -X PUT \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $GITHUB_TOKEN" \
                -H "X-Github-Api-Version: 2022-11-28" \
                "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews/${{ github.event.review.id }}" \
                -d '{"event": "dismissed", "message": "Commit authors cannot approve their own PRs."}'
              break
            fi
          done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token to authenticate API calls
